// src/components/Nav.tsx
import { useState, useEffect } from 'react';

const links = [
  { label: 'Sobre', href: '#sobre' },
  { label: 'Habilidades', href: '#habilidades' },
  { label: 'Projetos', href: '#projetos' },
  { label: 'Jornada', href: '#jornada' },
  { label: 'Contato', href: '#contato' },
];

export default function Nav() {
  const [scrolled, setScrolled] = useState(false);
  const [open, setOpen] = useState(false);

  useEffect(() => {
    const handler = () => setScrolled(window.scrollY > 40);
    window.addEventListener('scroll', handler, { passive: true });
    return () => window.removeEventListener('scroll', handler);
  }, []);

  return (
    <nav
      className="fixed top-0 left-0 right-0 z-50 transition-all duration-500"
      style={{
        background: scrolled
          ? 'rgba(9, 11, 17, 0.85)'
          : 'transparent',
        backdropFilter: scrolled ? 'blur(20px)' : 'none',
        borderBottom: scrolled ? '1px solid rgba(255,255,255,0.06)' : 'none',
      }}
    >
      <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
        {/* Logo */}
        <a href="#" className="flex items-center gap-2 group">
          <span
            className="w-7 h-7 rounded-lg flex items-center justify-center text-xs font-bold"
            style={{
              background: 'linear-gradient(135deg, #3b82f6, #8b5cf6)',
            }}
          >
            AS
          </span>
          <span className="font-semibold text-sm tracking-wide text-white/90 group-hover:text-white transition-colors">
            alexsantos.dev
          </span>
        </a>

        {/* Desktop links */}
        <div className="hidden md:flex items-center gap-8">
          {links.map((l) => (
            <a
              key={l.href}
              href={l.href}
              className="text-sm text-white/50 hover:text-white transition-colors duration-200 font-medium"
            >
              {l.label}
            </a>
          ))}
          <a
            href="#contato"
            className="text-sm font-semibold px-4 py-1.5 rounded-full transition-all duration-300 hover:scale-105"
            style={{
              background: 'linear-gradient(135deg, #3b82f6, #8b5cf6)',
              boxShadow: '0 0 20px rgba(139, 92, 246, 0.3)',
            }}
          >
            Hire me
          </a>
        </div>

        {/* Mobile toggle */}
        <button
          className="md:hidden text-white/70 hover:text-white transition-colors"
          onClick={() => setOpen(!open)}
          aria-label="Toggle menu"
        >
          <div className="flex flex-col gap-1.5 w-5">
            <span className={`block h-px bg-current transition-all duration-300 ${open ? 'rotate-45 translate-y-2' : ''}`} />
            <span className={`block h-px bg-current transition-all duration-300 ${open ? 'opacity-0' : ''}`} />
            <span className={`block h-px bg-current transition-all duration-300 ${open ? '-rotate-45 -translate-y-2' : ''}`} />
          </div>
        </button>
      </div>

      {/* Mobile menu */}
      <div
        className={`md:hidden transition-all duration-300 overflow-hidden`}
        style={{
          maxHeight: open ? '300px' : '0',
          background: 'rgba(9, 11, 17, 0.95)',
          backdropFilter: 'blur(20px)',
        }}
      >
        <div className="px-6 py-4 flex flex-col gap-4 border-t border-white/05">
          {links.map((l) => (
            <a
              key={l.href}
              href={l.href}
              onClick={() => setOpen(false)}
              className="text-sm text-white/60 hover:text-white transition-colors font-medium"
            >
              {l.label}
            </a>
          ))}
        </div>
      </div>
    </nav>
  );
}

// src/app/components/nav.component.ts
import { ChangeDetectionStrategy, Component, HostListener } from "@angular/core"

@Component({
  selector: "app-nav",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <nav class="fixed inset-x-0 top-0 z-50 transition-all duration-500" [style.background]="scrolled ? 'rgba(9,11,17,.85)' : 'transparent'" [style.backdrop-filter]="scrolled ? 'blur(20px)' : 'none'" [style.border-bottom]="scrolled ? '1px solid rgba(255,255,255,.06)' : 'none'">
      <div class="mx-auto flex h-16 max-w-6xl items-center justify-between px-6">
        <a href="#" class="group flex items-center gap-2"><span class="flex h-7 w-7 items-center justify-center rounded-lg bg-gradient-to-br from-blue-500 to-violet-500 text-xs font-bold">AS</span><span class="text-sm font-semibold tracking-wide text-white/90 transition-colors group-hover:text-white">alexsantos.dev</span></a>
        <div class="hidden items-center gap-8 md:flex">
          @for (link of links; track link.href) { <a [href]="link.href" class="text-sm font-medium text-white/50 transition-colors hover:text-white">{{ link.label }}</a> }
          <a href="#contato" class="rounded-full bg-gradient-to-br from-blue-500 to-violet-500 px-4 py-1.5 text-sm font-semibold shadow-[0_0_20px_rgba(139,92,246,.3)] transition-transform hover:scale-105">Hire me</a>
        </div>
        <button type="button" class="text-white/70 transition-colors hover:text-white md:hidden" (click)="open = !open" aria-label="Alternar menu" [attr.aria-expanded]="open">
          <span class="flex w-5 flex-col gap-1.5"><span class="block h-px bg-current transition-all" [class.translate-y-2]="open" [class.rotate-45]="open"></span><span class="block h-px bg-current transition-all" [class.opacity-0]="open"></span><span class="block h-px bg-current transition-all" [class.-translate-y-2]="open" [class.-rotate-45]="open"></span></span>
        </button>
      </div>
      <div class="overflow-hidden bg-[rgba(9,11,17,.95)] backdrop-blur-xl transition-all duration-300 md:hidden" [style.max-height]="open ? '300px' : '0'">
        <div class="flex flex-col gap-4 border-t border-white/5 px-6 py-4">@for (link of links; track link.href) { <a [href]="link.href" (click)="open = false" class="text-sm font-medium text-white/60 transition-colors hover:text-white">{{ link.label }}</a> }</div>
      </div>
    </nav>`,
})
export class NavComponent {
  readonly links = [
    { label: "Sobre", href: "#sobre" },
    { label: "Habilidades", href: "#habilidades" },
    { label: "Projetos", href: "#projetos" },
    { label: "Jornada", href: "#jornada" },
    { label: "Contato", href: "#contato" },
  ]
  scrolled = false
  open = false
  @HostListener("window:scroll") onScroll(): void {
    this.scrolled = window.scrollY > 40
  }
}
