// src/App.tsx
import Nav from './components/Nav';
import Hero from './components/Hero';
import About from './components/About';
import Skills from './components/Skills';
import Projects from './components/Projects';
import Timeline from './components/Timeline';
import Currently from './components/Currently';
import CTA from './components/CTA';
import Footer from './components/Footer';

export default function App() {
  return (
    <div style={{ background: '#090b11', minHeight: '100vh' }}>
      <Nav />
      <Hero />
      <About />
      <Skills />
      <Projects />
      <Timeline />
      <Currently />
      <CTA />
      <Footer />
    </div>
  );
}

// src/app/app.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core"
import { AboutComponent } from "./components/about.component"
import { CtaComponent } from "./components/cta.component"
import { CurrentlyComponent } from "./components/currently.component"
import { FooterComponent } from "./components/footer.component"
import { HeroComponent } from "./components/hero.component"
import { NavComponent } from "./components/nav.component"
import { ProjectsComponent } from "./components/projects.component"
import { SkillsComponent } from "./components/skills.component"
import { TimelineComponent } from "./components/timeline.component"

@Component({
  selector: "app-root",
  standalone: true,
  imports: [
    NavComponent,
    HeroComponent,
    AboutComponent,
    SkillsComponent,
    ProjectsComponent,
    TimelineComponent,
    CurrentlyComponent,
    CtaComponent,
    FooterComponent,
  ],
  template: `<main class="min-h-screen bg-[#090b11]"><app-nav /><app-hero /><app-about /><app-skills /><app-projects /><app-timeline /><app-currently /><app-cta /><app-footer /></main>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {}
