// src/app/components/cta.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core"
import { RevealDirective } from "../directives/reveal.directive"

@Component({
  selector: "app-cta",
  standalone: true,
  imports: [RevealDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<section id="contato" class="px-6 py-32"><div class="mx-auto max-w-4xl"><div appReveal [revealThreshold]=".2" class="reveal-scale relative overflow-hidden rounded-3xl border border-violet-500/20 bg-gradient-to-br from-blue-500/10 via-violet-500/15 to-emerald-500/[.08] p-8 text-center sm:p-12"><div class="pointer-events-none absolute inset-0 overflow-hidden"><div class="absolute -left-12 -top-24 h-[300px] w-[300px] rounded-full bg-[radial-gradient(circle,rgba(59,130,246,.15),transparent_70%)] blur-[30px]"></div><div class="absolute -bottom-20 -right-8 h-[250px] w-[250px] rounded-full bg-[radial-gradient(circle,rgba(16,185,129,.12),transparent_70%)] blur-[30px]"></div></div><div class="relative z-10"><div class="mb-8 inline-flex items-center gap-2 rounded-full border border-emerald-500/25 bg-emerald-500/[.08] px-4 py-1.5 text-xs font-medium text-emerald-500"><span class="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-400"></span>Disponível para freelance e full-time</div><h2 class="mb-4 font-bold tracking-[-.03em] [font-size:clamp(2rem,5vw,3.5rem)]">Vamos construir algo <span class="gradient-text">incrível</span></h2><p class="mx-auto mb-10 max-w-xl leading-relaxed text-white/55">Tenho interesse em projetos desafiadores, oportunidades de tech lead e colaborações com times de alta performance. Se você tem um problema complexo, quero ouvir.</p><div class="mb-12 flex flex-wrap justify-center gap-4"><a href="mailto:alex@alexsantos.dev" class="rounded-full bg-gradient-to-br from-blue-500 to-violet-500 px-8 py-4 font-semibold shadow-[0_0_40px_rgba(139,92,246,.4)] transition-transform hover:scale-105">alex&#64;alexsantos.dev</a><a href="#" class="rounded-full border border-white/15 bg-white/[.05] px-8 py-4 font-semibold text-white/80 transition-all hover:scale-105 hover:border-white/25">Agendar conversa</a></div><div class="flex flex-wrap justify-center gap-6 border-t border-white/[.06] pt-8">@for(info of infos;track info){<div class="flex items-center gap-2 text-sm text-white/45"><span class="h-1.5 w-1.5 rounded-full bg-violet-400"></span>{{info}}</div>}</div></div></div></div></section>`,
})
export class CtaComponent {
  readonly infos = [
    "Resposta em até 24h",
    "Trabalho 100% remoto",
    "GMT-3 · São Paulo",
  ]
}

// src/components/CTA.tsx
import { useReveal } from '../hooks/useReveal';

export default function CTA() {
  const ref = useReveal(0.2) as React.RefObject<HTMLDivElement>;

  return (
    <section id="contato" className="py-32 px-6">
      <div className="max-w-4xl mx-auto">
        <div
          ref={ref as any}
          className="reveal-scale relative rounded-3xl overflow-hidden p-12 text-center"
          style={{
            background: 'linear-gradient(135deg, rgba(59,130,246,0.1) 0%, rgba(139,92,246,0.15) 50%, rgba(16,185,129,0.08) 100%)',
            border: '1px solid rgba(139,92,246,0.2)',
          }}
        >
          {/* Background orbs inside card */}
          <div className="absolute inset-0 pointer-events-none overflow-hidden">
            <div
              className="absolute rounded-full"
              style={{
                width: '300px',
                height: '300px',
                top: '-100px',
                left: '-50px',
                background: 'radial-gradient(circle, rgba(59,130,246,0.15) 0%, transparent 70%)',
                filter: 'blur(30px)',
              }}
            />
            <div
              className="absolute rounded-full"
              style={{
                width: '250px',
                height: '250px',
                bottom: '-80px',
                right: '-30px',
                background: 'radial-gradient(circle, rgba(16,185,129,0.12) 0%, transparent 70%)',
                filter: 'blur(30px)',
              }}
            />
          </div>

          {/* Grid pattern */}
          <div
            className="absolute inset-0 pointer-events-none"
            style={{
              backgroundImage: `
                linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px),
                linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px)
              `,
              backgroundSize: '40px 40px',
              maskImage: 'radial-gradient(ellipse at center, black, transparent)',
            }}
          />

          <div className="relative z-10">
            {/* Status */}
            <div
              className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border text-xs font-medium mb-8"
              style={{
                background: 'rgba(16,185,129,0.08)',
                borderColor: 'rgba(16,185,129,0.25)',
                color: '#10b981',
              }}
            >
              <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
              Disponível para freelance e full-time
            </div>

            <h2
              className="font-bold mb-4"
              style={{ fontSize: 'clamp(2rem, 5vw, 3.5rem)', letterSpacing: '-0.03em' }}
            >
              Vamos construir algo{' '}
              <span
                style={{
                  background: 'linear-gradient(135deg, #60a5fa, #a78bfa, #34d399)',
                  WebkitBackgroundClip: 'text',
                  WebkitTextFillColor: 'transparent',
                  backgroundClip: 'text',
                }}
              >
                incrível
              </span>
            </h2>

            <p className="text-white/55 max-w-xl mx-auto leading-relaxed mb-10">
              Tenho interesse em projetos desafiadores, oportunidades de tech lead e colaborações
              com times de alta performance. Se você tem um problema complexo, quero ouvir.
            </p>

            <div className="flex flex-wrap gap-4 justify-center mb-12">
              <a
                href="mailto:alex@alexsantos.dev"
                className="group flex items-center gap-2 px-8 py-4 rounded-full font-semibold transition-all duration-300 hover:scale-105"
                style={{
                  background: 'linear-gradient(135deg, #3b82f6, #8b5cf6)',
                  boxShadow: '0 0 40px rgba(139, 92, 246, 0.4)',
                }}
              >
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                </svg>
                alex@alexsantos.dev
              </a>
              <a
                href="#"
                className="flex items-center gap-2 px-8 py-4 rounded-full font-semibold border transition-all duration-300 hover:scale-105 hover:border-white/25"
                style={{
                  borderColor: 'rgba(255,255,255,0.15)',
                  background: 'rgba(255,255,255,0.05)',
                  color: 'rgba(255,255,255,0.8)',
                }}
              >
                Agendar conversa
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
              </a>
            </div>

            {/* Quick info */}
            <div
              className="flex flex-wrap gap-6 justify-center"
              style={{ borderTop: '1px solid rgba(255,255,255,0.06)', paddingTop: '32px' }}
            >
              {[
                { icon: '⚡', text: 'Resposta em até 24h' },
                { icon: '🌎', text: 'Trabalho 100% remoto' },
                { icon: '🕐', text: 'GMT-3 · São Paulo' },
              ].map((info) => (
                <div key={info.text} className="flex items-center gap-2 text-sm text-white/45">
                  <span>{info.icon}</span>
                  <span>{info.text}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
