// src/app/components/timeline.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core"
import { RevealDirective } from "../directives/reveal.directive"

@Component({
  selector: "app-timeline",
  standalone: true,
  imports: [RevealDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<section id="jornada" class="relative px-6 py-32"><div class="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_60%_80%_at_30%_50%,rgba(59,130,246,.04),transparent_70%)]"></div><div class="relative mx-auto max-w-4xl"><div appReveal class="reveal mb-20 text-center"><span class="inline-block rounded-full border border-emerald-500/20 bg-emerald-500/10 px-3 py-1 font-mono text-xs font-medium text-emerald-400">04 — Jornada</span><h2 class="mt-3 font-bold tracking-[-.02em] [font-size:clamp(2rem,4vw,2.8rem)]">Linha do <span class="bg-gradient-to-br from-emerald-400 to-blue-400 bg-clip-text text-transparent">tempo</span></h2><p class="mt-4 leading-relaxed text-white/45">Da faculdade ao tech lead — 6 anos de crescimento contínuo.</p></div>
<div class="relative"><div class="timeline-line hidden md:block"></div>@for(event of events;track event.title;let i=$index){<div class="relative flex flex-row" [class.md:flex-row-reverse]="i%2===1"><div class="flex-1 pl-10 md:px-12"><article appReveal class="card-hover mb-8 rounded-2xl border border-white/[.06] bg-white/[.02] p-5" [class.reveal-left]="i%2===0" [class.reveal-right]="i%2===1"><div class="mb-2 flex items-center gap-2"><span class="font-mono text-xs" [style.color]="event.color">{{event.year}}</span><span class="h-1 w-1 rounded-full bg-white/20"></span><span class="text-xs uppercase tracking-wider text-white/35">{{event.type}}</span></div><h3 class="mb-2 text-sm font-semibold leading-snug text-white/90">{{event.title}}</h3><p class="text-xs leading-relaxed text-white/50">{{event.desc}}</p></article></div><div class="absolute left-0 flex flex-col items-center md:relative md:left-auto md:w-0"><span class="z-10 mt-[22px] h-3 w-3 rounded-full" [style.background]="event.color" [style.box-shadow]="'0 0 12px '+event.color+'60'"></span></div><div class="hidden flex-1 md:block"></div></div>}</div></div></section>`,
})
export class TimelineComponent {
  readonly events = [
    {
      year: "2024",
      title: "Tech Lead @ Nuvem Digital",
      desc: "Liderança técnica de um time de 6 engenheiros. Arquitetura de plataforma de pagamentos que processa R$50M/mês. Migração para microserviços com zero downtime.",
      type: "Trabalho",
      color: "#3b82f6",
    },
    {
      year: "2023",
      title: "Senior Dev @ Loja Fácil",
      desc: "Desenvolvimento do novo checkout Loja Fácil. Redução de 40% no abandono de carrinho. Stack: React, Node.js, PostgreSQL.",
      type: "Trabalho",
      color: "#8b5cf6",
    },
    {
      year: "2022",
      title: "Lançamento Flowkit UI",
      desc: "Criação e lançamento do design system open source que acumulou 3k+ stars no GitHub em 6 meses.",
      type: "Projeto",
      color: "#10b981",
    },
    {
      year: "2021",
      title: "Mid-level Dev @ Startup XYZ",
      desc: "Desenvolvimento de plataforma SaaS B2B de RH. Responsável pelo módulo de relatórios e integrações com ERPs.",
      type: "Trabalho",
      color: "#8b5cf6",
    },
    {
      year: "2020",
      title: "AWS Certified Solutions Architect",
      desc: "Certificação AWS – Associate e início das especializações em arquitetura cloud e infraestrutura como código.",
      type: "Certificação",
      color: "#f59e0b",
    },
    {
      year: "2019",
      title: "Primeiro emprego — Junior Dev",
      desc: "Desenvolvedor júnior em agência digital. Primeiros projetos reais com React e Node. Aprendizado intenso sobre entrega e deadline.",
      type: "Trabalho",
      color: "#3b82f6",
    },
    {
      year: "2018",
      title: "Bacharel em Ciência da Computação",
      desc: "Formação pela Universidade de São Paulo. TCC sobre otimização de consultas em bancos de dados distribuídos.",
      type: "Formação",
      color: "#a78bfa",
    },
  ]
}

// src/components/Timeline.tsx
import { useReveal } from '../hooks/useReveal';

const events = [
  {
    year: '2024',
    title: 'Tech Lead @ Nuvem Digital',
    desc: 'Liderança técnica de um time de 6 engenheiros. Arquitetura de plataforma de pagamentos que processa R$50M/mês. Migração para microserviços com zero downtime.',
    type: 'work',
    color: '#3b82f6',
  },
  {
    year: '2023',
    title: 'Senior Dev @ Loja Fácil',
    desc: 'Desenvolvimento do novo checkout Loja Fácil. Redução de 40% no abandono de carrinho. Stack: React, Node.js, PostgreSQL.',
    type: 'work',
    color: '#8b5cf6',
  },
  {
    year: '2022',
    title: 'Lançamento Flowkit UI',
    desc: 'Criação e lançamento do design system open source que acumulou 3k+ stars no GitHub em 6 meses.',
    type: 'project',
    color: '#10b981',
  },
  {
    year: '2021',
    title: 'Mid-level Dev @ Startup XYZ',
    desc: 'Desenvolvimento de plataforma SaaS B2B de RH. Responsável pelo módulo de relatórios e integrações com ERPs.',
    type: 'work',
    color: '#8b5cf6',
  },
  {
    year: '2020',
    title: 'AWS Certified Solutions Architect',
    desc: 'Certificação AWS – Associate e início das especializações em arquitetura cloud e infraestrutura como código.',
    type: 'cert',
    color: '#f59e0b',
  },
  {
    year: '2019',
    title: 'Primeiro emprego — Junior Dev',
    desc: 'Desenvolvedor júnior em agência digital. Primeiros projetos reais com React e Node. Aprendizado intenso sobre entrega e deadline.',
    type: 'work',
    color: '#3b82f6',
  },
  {
    year: '2018',
    title: 'Bacharel em Ciência da Computação',
    desc: 'Formação pela Universidade de São Paulo. TCC sobre otimização de consultas em bancos de dados distribuídos.',
    type: 'education',
    color: '#a78bfa',
  },
];

const typeIcon: Record<string, string> = {
  work: '💼',
  project: '🚀',
  cert: '🏆',
  education: '🎓',
};

function TimelineItem({ event, side }: { event: typeof events[0]; side: 'left' | 'right' }) {
  const ref = useReveal(0.15) as React.RefObject<HTMLDivElement>;

  return (
    <div
      className={`relative flex ${side === 'left' ? 'md:flex-row-reverse' : 'md:flex-row'} flex-row gap-0`}
    >
      {/* Card side */}
      <div className={`flex-1 ${side === 'left' ? 'md:pr-12 md:pl-0' : 'md:pl-12 md:pr-0'} pl-10 pr-0`}>
        <div
          ref={ref as any}
          className={`${side === 'left' ? 'reveal-right' : 'reveal-left'} card-hover p-5 rounded-2xl mb-8`}
          style={{
            background: 'rgba(255,255,255,0.02)',
            border: '1px solid rgba(255,255,255,0.06)',
          }}
        >
          <div className="flex items-center gap-2 mb-2">
            <span className="text-xs font-mono" style={{ color: event.color }}>
              {event.year}
            </span>
            <span
              className="w-1 h-1 rounded-full"
              style={{ background: 'rgba(255,255,255,0.2)' }}
            />
            <span className="text-xs text-white/35">{typeIcon[event.type]}</span>
          </div>
          <h3 className="font-semibold text-white/90 mb-2 text-sm leading-snug">{event.title}</h3>
          <p className="text-xs text-white/50 leading-relaxed">{event.desc}</p>
        </div>
      </div>

      {/* Center dot */}
      <div className="absolute left-0 md:relative md:left-auto md:flex-none md:w-0 flex flex-col items-center">
        <div
          className="w-3 h-3 rounded-full mt-5 shrink-0 z-10"
          style={{
            background: event.color,
            boxShadow: `0 0 12px ${event.color}60`,
            marginTop: '22px',
          }}
        />
      </div>

      {/* Empty side */}
      <div className="flex-1 hidden md:block" />
    </div>
  );
}

export default function Timeline() {
  const titleRef = useReveal() as React.RefObject<HTMLDivElement>;

  return (
    <section id="jornada" className="py-32 px-6 relative">
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          background: 'radial-gradient(ellipse 60% 80% at 30% 50%, rgba(59,130,246,0.04) 0%, transparent 70%)',
        }}
      />

      <div className="max-w-4xl mx-auto relative">
        <div ref={titleRef as any} className="reveal text-center mb-20">
          <span
            className="font-mono text-xs font-medium px-3 py-1 rounded-full mb-4 inline-block"
            style={{
              background: 'rgba(16,185,129,0.1)',
              color: '#34d399',
              border: '1px solid rgba(16,185,129,0.2)',
            }}
          >
            04 — Jornada
          </span>
          <h2
            className="font-bold mt-3"
            style={{ fontSize: 'clamp(2rem, 4vw, 2.8rem)', letterSpacing: '-0.02em' }}
          >
            Linha do{' '}
            <span
              style={{
                background: 'linear-gradient(135deg, #34d399, #60a5fa)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
              }}
            >
              tempo
            </span>
          </h2>
          <p className="text-white/45 mt-4 leading-relaxed">
            Da faculdade ao tech lead — 6 anos de crescimento contínuo.
          </p>
        </div>

        {/* Timeline */}
        <div className="relative">
          {/* Vertical line — desktop only */}
          <div className="timeline-line hidden md:block" />

          <div>
            {events.map((e, i) => (
              <TimelineItem key={e.title} event={e} side={i % 2 === 0 ? 'right' : 'left'} />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
